import os
import json
from fastapi import FastAPI, UploadFile, BackgroundTasks
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from models import EditorialArticle
from typing import List, Optional
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="The Sentinel API", description="AI-Native Newsroom Engine powered by Virlo")

# Static files for the frontend (vanilla HTML/CSS/JS)
try:
    app.mount("/static", StaticFiles(directory="static"), name="static")
except RuntimeError:
    print("Warning: /static directory does not exist yet. Create it for the frontend assets.")

@app.get("/api/articles", response_model=List[EditorialArticle])
def get_articles(niche: Optional[str] = None):
    """
    Returns the latest deep-dive articles generated by the Editorial Agent.
    """
    if not os.path.exists("database.json"):
        return []
        
    try:
        with open("database.json", "r") as f:
            data = json.load(f)
            
        articles = [EditorialArticle(**item) for item in data]
        if niche:
            articles = [a for a in articles if a.niche.lower() == niche.lower()]
            
        return articles
    except Exception as e:
        print(f"Error loading articles: {e}")
        return []

class ChatRequest(BaseModel):
    article_id: str
    question: str

@app.post("/api/chat")
def article_chat(request: ChatRequest):
    """
    Phase 3: The Conversational Layer.
    Allows users to interrogate an article using the Virlo client.
    """
    # In a real app we'd fetch the article content and fact sheet to inject context into the prompt
    # and use the VirloClient to generate the answer.
    from virlo_client import VirloClient
    virlo = VirloClient()
    
    system_prompt = "You are 'The Sentinel' Q&A bot. Answer questions accurately based strictly on the article content."
    prompt = f"User asks: {request.question}"
    
    # Normally we pass the article data too.
    answer = virlo.generate(system_prompt, prompt, temperature=0.2)
    
    return {"response": answer}

if __name__ == "__main__":
    import uvicorn
    # Start the local server
    print("Serving The Sentinel on http://localhost:8000 ...")
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
